//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void DAC0_enter_DefaultMode_from_RESET(void);
extern void BURTC_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void OPAMP0_enter_DefaultMode_from_RESET(void);
extern void OPAMP1_enter_DefaultMode_from_RESET(void);
extern void OPAMP2_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void USART2_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void LEUART1_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void I2C1_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void TIMER2_enter_DefaultMode_from_RESET(void);
extern void TIMER3_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PCNT1_enter_DefaultMode_from_RESET(void);
extern void PCNT2_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void ETM_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define I2C0_SCL_PIN        (13)
#define I2C0_SCL_PORT       (gpioPortE)

#define I2C0_SDA_PIN        (12)
#define I2C0_SDA_PORT       (gpioPortE)

#define INIC_GP1_PIN        (9)
#define INIC_GP1_PORT       (gpioPortA)

#define INIC_GP2_PIN        (10)
#define INIC_GP2_PORT       (gpioPortA)

#define INIC_GP3_PIN        (0)
#define INIC_GP3_PORT       (gpioPortD)

#define INIC_GP4_PIN        (1)
#define INIC_GP4_PORT       (gpioPortD)

#define INIC_GP5_PIN        (2)
#define INIC_GP5_PORT       (gpioPortD)

#define INIC_GP6_PIN        (2)
#define INIC_GP6_PORT       (gpioPortA)

#define INIC_GP7_PIN        (3)
#define INIC_GP7_PORT       (gpioPortD)

#define INIC_GP8_PIN        (11)
#define INIC_GP8_PORT       (gpioPortE)

#define JOG_ENCA_PIN        (6)
#define JOG_ENCA_PORT       (gpioPortD)

#define JOG_ENCB_PIN        (7)
#define JOG_ENCB_PORT       (gpioPortD)

#define JOG_PUSH_PIN        (5)
#define JOG_PUSH_PORT       (gpioPortF)

#define MGC_MCLR_PIN        (15)
#define MGC_MCLR_PORT       (gpioPortE)

#define MGC_TS_PIN          (1)
#define MGC_TS_PORT         (gpioPortA)

#define USART1_RX_PIN       (1)
#define USART1_RX_PORT      (gpioPortC)

#define USART1_TX_PIN       (0)
#define USART1_TX_PORT      (gpioPortC)

// [User-defined pin name abstraction]$

#endif

